### ISSUE TITLE
Session ends up randomly after 5minutes

### ISSUE THREAD

**Issue by zrk571** [play-with-docker/play-with-docker#356]
**Description:**
I'm currently trying to use this plateform to test a basic docker-compose tutorial ([https://docs.docker.com/compose/wordpress/](https://docs.docker.com/compose/wordpress/)) but session ends up after several minutes between3 and 5. It seems to be unstable ?

**Steps to reproduce:**

`docker-compose up -d`

With `docker-compose.yml` data :

```
version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
```

**Environnement:**

Key | Value
-- | --
Operating system | Windows NT 7.0
Javascript enabled | Yes
Cookies enabled | Yes
Flash version | Not installed
Java version | Not installed
Websockets supported | Yes
Screen size | 1280 x 720 (Retina)
Color depth | 24 bit
Timezone | Europe/Paris
User Agent | Mozilla/5.0 (Windows NT 7.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
