### ISSUE TITLE
Unable to open any applications using Docker-Compose

### ISSUE THREAD

**Issue by shimizurei** [play-with-docker/play-with-docker#503]
I have tried multiple compose files for various programs under various instances. Not a single page is opening for me.

Even something as straightforward as this I cannot open:

```
version: '3.1'
services:
  mealie:
    image: 'hkotel/mealie:latest'
    container_name: mealie
    restart: always
    ports:
      - '6767:80'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - 'data:/app/data'
```

Everything runs, the port is opened, but when clicked, it's just an endless loading page. Updated my browser, used the guest one with no extensions, nothing.
