### ISSUE TITLE
Unable to load app pages

### ISSUE THREAD

**Issue by shimizurei** [play-with-docker/play-with-docker#524]
## Replicate

Visit: https://labs.play-with-docker.com

Browsers: 

- Google Chrome guest browser (Version 101.0.4951.67 (Official Build) (64-bit)) with no extensions/add-ons
- Mozilla Firefox Version 100.0.2 (64-bit)

`touch docker-compose.yml && mkdir data`

Example docker-compose I use that has never had issues working

```
version: '3.1'
services:
  mealie:
    image: 'hkotel/mealie:latest'
    container_name: mealie
    restart: always
    ports:
      - '8999:80'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      RECIPE_DISABLE_COMMENTS: 'true'
    volumes:
      - '/root/data:/app/data'
```

`docker-compose up -d`

No issues with the pull. 

---

When I click the port number, it loads endlessly and then the following error occurs:

Chrome: `This site can’t be reached - ip172-18-0-13-ca5jkto9jotg00b0722g-8999.direct.labs.play-with-docker.com took too long to respond.`

Firefox: `Unable to connect - An error occurred during a connection to ip172-18-0-120-ca5js9c33d5g008v1gpg-8999.direct.labs.play-with-docker.com.`

Doing `docker logs -f [CONTAINER ID]` shows that the application itself has completed startup, but the page isn't opening. This is an application I've never had issues opening and it's not like my previous issue #522 where the setup was extremely resource-heavy. Is there a problem on the backend? I tried testing at least 6 different apps yesterday, to no avail.

**Comment by marcosnils** [comment]
should work now

**Comment by ChubaOraka** [comment]
I'm now getting **This site can’t be reached** or **502 Bad Gateway** errors when I try to access the frontend of an app spun up on PWD.

**Comment by marcosnils** [comment]
I was doing some maintenance on the server. Should work now

**Comment by shimizurei** [comment]
Not working.

Tested with the following (with and without version line, on the latest Chrome and Firefox):

```
version: '3'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    ports:
      - 9779:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Logs show that dozzle is working, but the page can't be accessed.
![dozzle](https://user-images.githubusercontent.com/3500094/180714174-f99b4f78-fd58-483c-a9e0-df90990d279a.PNG)
