### ISSUE TITLE
Any tips on how to tunnel pwd through VPN?

### ISSUE THREAD

**Issue by exactsameproblem** [play-with-docker/play-with-docker#526]
Hello there,
I would like to pass all the containers created inside PWD through a VPN.
I edited the docker compose file to reflect the changes (see code below).

I tried different things like:
- removing haproxy in order to reach the vpn service first and redirect it to PWD : I can't reach the backend even while specifying port 3000 in the playground domain : INTERNET -> Cloudflare domain -> VPN -> PWD 
- putting the VPN in front of haproxy - not sure on how to redirect ports together : INTERNET -> Cloudflare domain -> VPN -> haproxy-> PWD
- adding a new frontend and backend to haproxy: INTERNET -> Cloudflare -> haproxy -> VPN -> haproxy -> PWD

On my playground domain page, I either get "503", "521" or "522 timeout" errors.

I'm using cloudflare with a ssl key configured inside haproxy, so the "normal" setup (without the vpn service) **works like a charm**, but I cannot pass pwd **inside the VPN** and reach it **outside of localhost** (by using the **playground domain through cloudflare**).

Here is my docker compose file:
```
version: '3.2'
services:
    haproxy:
        container_name: haproxy
        image: haproxy
        ports:
           - "80:8080" # http-in
           - "443:443" # https-in with ssl cert (cloudflare)
        volumes:
           - ./haproxy:/usr/local/etc/haproxy

vpn:
        depends_on:
            - haproxy
        container_name: nordvpn
        image: azinchen/nordvpn:latest
        cap_add:
            - net_admin
        devices:
            - /dev/net/tun
        environment:
           - USER=mail
           - PASS=pass
           - COUNTRY=Germany;IE;131
           - GROUP=Standard VPN servers
           - RANDOM_TOP=10
           - RECREATE_VPN_CRON=5 */3 * * *
           - NETWORK=172.26.0.0/16;177.17.0.0/16;177.20.0.0/16 # tried differents ip with no sucess
           - OPENVPN_OPTS=--mute-replay-warnings
     
        restart: unless-stopped

 pwd:
        depends_on:
            - vpn
        network_mode: service:vpn 
        # pwd daemon container always needs to be named this way
        container_name: pwd
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/; if [ -e /runbin/pwd ]; then /runbin/pwd  -save /pwd/sessions -name l2; else go run api.go -save /pwd/sessions -name l2; fi'
        volumes:
            # since this app creates networks and launches containers, we need to talk to docker daemon
            - /var/run/docker.sock:/var/run/docker.sock
            # mount the box mounted shared folder to the container
            - $PWD:/go/src
            - sessions:/pwd

    l2:
        depends_on:
            - vpn2
        network_mode: service:vpn2	
        container_name: l2
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/router/l2; if [ -e /runbin/l2 ]; then /runbin/l2 -ssh_key_path /etc/ssh/ssh_host_rsa_key -name l2 -save /pwd/networks; else go run l2.go -ssh_key_path /etc/ssh/ssh_host_rsa_key -name l2 -save /pwd/networks; fi'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD:/go/src
            - networks:/pwd
        ports:
            - "8022:22"
            - "8053:53"   

volumes:
    sessions:
    networks:
```

Any help on how it would be possible to achieve this?
Thank you.
