### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by shimizurei** [play-with-docker/play-with-docker#543]
I know that maintainence was being done ~16+ hours ago, but the app still doesn't work. I tested with a program that requires very little.

Tested with the following (with and without version line, on the latest Chrome and Firefox):

```
version: '3'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    ports:
      - 9779:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Logs show that dozzle is working, but the page can't be accessed.
![dozzle](https://user-images.githubusercontent.com/3500094/180714174-f99b4f78-fd58-483c-a9e0-df90990d279a.PNG)
