### ISSUE TITLE
ssh using github action appleboy/ssh-action 

### ISSUE THREAD

**Issue by foremtehan** [play-with-docker/play-with-docker#556]
I want to ssh into server using  this github action https://github.com/appleboy/ssh-action, With following config:

```
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        with:
          host: direct.labs.play-with-docker.com
          username: ip172-18-0-018-cd3jsnm1tccg00b3sbjg
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          script: |
            docker composer up -d --build
```

But i'll get the following error:

```
======CMD======
docker composer up -d --build

======END======
err: Connecting to 20.228.211.183:8022
out: 
out: 
err: 
err: 
2022/10/14 14:20:49 wait: remote command exited without exit status or exit signal
err: 
err: 
err: 
err: 
out: 
err: 
out: 
out: 
out: 
out: 
out: 
err: 
out: 
err: 
out: 
out: 
err: 
out: 
out: 
err: 
err: 
err: 
err: 
err: 
err: 
err: 
out: 
out: 
err: 
out: 
out: 
err: 
out: 
err: 
out: 
err: 
err: 
```
